/**
 * Stub for @convex/_generated/api.
 * The real file is generated by `pnpm convex dev` and is gitignored.
 * Tests import this stub so they never need a running Convex backend.
 *
 * Exported structure mirrors the shape that components expect:
 *   api.users.viewer  → used by AppShell
 *   api.gyms.*        → used by GymCombobox
 *   api.sessions.*    → used by LogSessionForm, session pages
 */
export const api = {
  users: {
    viewer: 'users:viewer',
  },
  gyms: {
    list: 'gyms:list',
    listByPrefix: 'gyms:listByPrefix',
    ensureByName: 'gyms:ensureByName',
  },
  sessions: {
    createSession: 'sessions:createSession',
    updateSession: 'sessions:updateSession',
    get: 'sessions:get',
    list: 'sessions:list',
  },
  dashboard: {
    stats: 'dashboard:stats',
  },
  reports: {
    list: 'reports:list',
    get: 'reports:get',
  },
  follows: {
    list: 'follows:list',
  },
} as const;
